# Generated by Django 5.1.1 on 2024-09-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Userauth',
        ),
    ]
