# Generated by Django 5.1.1 on 2024-09-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_rename_member_userauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
