# Generated by Django 5.1.1 on 2024-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userauth_joined_date_userauth_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='useremail',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
